# Generated by Django 6.0.2 on 2026-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bvhjob',
            name='pipeline',
            field=models.CharField(choices=[('mediapipe', 'MediaPipe (CPU, fast)'), ('openpose', 'OpenPose (GPU/CUDA, accurate)')], default='mediapipe', max_length=20),
        ),
        migrations.AlterField(
            model_name='bvhjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('openpose', 'Running OpenPose'), ('openpose_csv', 'Converting OpenPose JSON'), ('mediapipe', 'Running MediaPipe'), ('mocapnet', 'Running MocapNET'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
