# Generated by Django 6.0.2 on 2026-02-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bvhjob_pipeline_alter_bvhjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_update_interval', models.IntegerField(default=50, help_text='Update progress every N frames during MediaPipe/OpenPose processing')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.AddField(
            model_name='bvhjob',
            name='progress_detail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
