# Generated by Django 6.0.2 on 2026-02-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appsettings_bvhjob_progress_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='progress_update_interval',
            field=models.IntegerField(default=10, help_text='Update progress every N frames during MediaPipe/OpenPose processing'),
        ),
        migrations.AlterField(
            model_name='bvhjob',
            name='pipeline',
            field=models.CharField(choices=[('mediapipe', 'MediaPipe (CPU, fast)'), ('openpose', 'OpenPose (GPU/CUDA, accurate)'), ('v4', 'MocapNET v4 (Full Body)')], default='mediapipe', max_length=20),
        ),
        migrations.AlterField(
            model_name='bvhjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('openpose', 'Running OpenPose'), ('openpose_csv', 'Converting OpenPose JSON'), ('mediapipe', 'Running MediaPipe'), ('mocapnet', 'Running MocapNET'), ('v4_processing', 'Running MocapNET v4'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
