# Generated by Django 6.0.2 on 2026-02-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appsettings_progress_update_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='default_model_animations',
            field=models.CharField(blank=True, default='femaleWithClothes', help_text='Default model preset for Animationen page', max_length=200),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_model_config',
            field=models.CharField(blank=True, default='femaleWithClothes', help_text='Default model preset for Konfiguration page', max_length=200),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_model_scene',
            field=models.CharField(blank=True, default='femaleWithClothes', help_text='Default model preset for Szene page', max_length=200),
        ),
    ]
