# Generated by Django 6.0.2 on 2026-02-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appsettings_default_model_animations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='default_anim_animations',
            field=models.CharField(blank=True, default='', help_text='Default animation URL for Animationen page', max_length=300),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_anim_config',
            field=models.CharField(blank=True, default='', help_text='Default animation URL for Konfiguration page', max_length=300),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_anim_scene',
            field=models.CharField(blank=True, default='', help_text='Default animation URL for Szene page', max_length=300),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='show_rig_animations',
            field=models.BooleanField(default=False, help_text='Show rig by default on Animationen page'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='show_rig_config',
            field=models.BooleanField(default=False, help_text='Show rig by default on Konfiguration page'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='show_rig_scene',
            field=models.BooleanField(default=False, help_text='Show rig by default on Szene page'),
        ),
    ]
