# Generated by Django 6.0.2 on 2026-02-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_appsettings_default_anim_animations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='expanded_panels_config',
            field=models.CharField(blank=True, default='["body_type","morphs","cloth_template"]', help_text='JSON list of expanded panel keys for Konfiguration page', max_length=500),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='expanded_panels_scene',
            field=models.CharField(blank=True, default='["beleuchtung","renderer","kamera","material_skin","aktionen"]', help_text='JSON list of expanded panel keys for Szene page', max_length=500),
        ),
    ]
