# Generated by Django 6.0.2 on 2026-02-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appsettings_expanded_panels_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='mp_min_detection_confidence',
            field=models.FloatField(default=0.5, help_text='Pose detection confidence threshold (0.0–1.0)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mp_min_tracking_confidence',
            field=models.FloatField(default=0.2, help_text='Pose tracking confidence (0.0–1.0)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mp_model_complexity',
            field=models.IntegerField(default=1, help_text='0=Lite (fast), 1=Full (accurate)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='v4_hcd_epochs',
            field=models.IntegerField(default=30, help_text='IK epochs per frame (1–200)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='v4_hcd_iterations',
            field=models.IntegerField(default=10, help_text='IK gradient descent iterations per frame (1–100)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='v4_hcd_learning_rate',
            field=models.FloatField(default=0.001, help_text='IK learning rate (0.0001–0.1)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='v4_smoothing_cutoff',
            field=models.FloatField(default=5.0, help_text='Butterworth low-pass cutoff Hz (0.5–15.0)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='v4_smoothing_sampling',
            field=models.FloatField(default=30.0, help_text='Butterworth sampling Hz (10.0–120.0)'),
        ),
    ]
