# Generated by Django 6.0.2 on 2026-02-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appsettings_mp_min_detection_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='detector_2d_default',
            field=models.CharField(default='mediapipe', help_text='Default 2D detector (mediapipe/openpose/rtmpose/vitpose/yolo11)', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='lifter_3d_default',
            field=models.CharField(default='v4', help_text='Default 3D pipeline (v4/gvhmr/wham/prompthmr)', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='rtmpose_model_size',
            field=models.CharField(default='l', help_text='RTMPose model size: m, l, x', max_length=5),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='vitpose_model_size',
            field=models.CharField(default='h', help_text='ViTPose model size: b, l, h', max_length=5),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='yolo_model_size',
            field=models.CharField(default='l', help_text='YOLO11-Pose model size: n, s, m, l, x', max_length=5),
        ),
        migrations.AlterField(
            model_name='bvhjob',
            name='pipeline',
            field=models.CharField(choices=[('mediapipe', 'MediaPipe'), ('openpose', 'OpenPose'), ('rtmpose', 'RTMPose'), ('vitpose', 'ViTPose'), ('yolo11', 'YOLO11-Pose'), ('v4', 'MocapNET v4'), ('gvhmr', 'GVHMR'), ('wham', 'WHAM'), ('prompthmr', 'PromptHMR')], default='mediapipe', max_length=20),
        ),
        migrations.AlterField(
            model_name='bvhjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('detecting_2d', '2D Detection'), ('openpose', 'Running OpenPose'), ('openpose_csv', 'Converting OpenPose JSON'), ('mediapipe', 'Running MediaPipe'), ('lifting_3d', '3D Lifting'), ('mocapnet', 'Running MocapNET'), ('v4_processing', 'Running MocapNET v4'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
