# Generated by Django 6.0.2 on 2026-02-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appsettings_detector_2d_default_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bvhjob',
            index=models.Index(fields=['status'], name='core_bvhjob_status_2ff48a_idx'),
        ),
        migrations.AddIndex(
            model_name='bvhjob',
            index=models.Index(fields=['pipeline', '-created_at'], name='core_bvhjob_pipelin_d59d3a_idx'),
        ),
    ]
