# Generated by Django 6.0.2 on 2026-02-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bvhjob_core_bvhjob_status_2ff48a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='smpl_device',
            field=models.CharField(default='cuda', help_text='Device for SMPL pipelines (cuda/cpu)', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='v4_enable_body',
            field=models.BooleanField(default=True, help_text='Enable body tracking'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='v4_enable_eyes',
            field=models.BooleanField(default=False, help_text='Enable eye tracking'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='v4_enable_face',
            field=models.BooleanField(default=True, help_text='Enable face tracking'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='v4_enable_hands',
            field=models.BooleanField(default=True, help_text='Enable hand tracking'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='v4_enable_mouth',
            field=models.BooleanField(default=True, help_text='Enable mouth tracking'),
        ),
    ]
