# Generated by Django 6.0.2 on 2026-02-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_v4_components_smpl_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='gvhmr_focal_length_mm',
            field=models.FloatField(default=26.0, help_text='Camera focal length in mm (default 26)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gvhmr_static_cam',
            field=models.BooleanField(default=True, help_text='Skip DPVO dynamic camera estimation (static camera)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='prompthmr_static_camera',
            field=models.BooleanField(default=True, help_text='Assume static camera (recommended for most videos)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='video_output_dir',
            field=models.CharField(blank=True, default='A:\\3DTools\\HumanBodyWeb\\media\\output', help_text='Directory for saving 3D video exports from the Process result page', max_length=500),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='wham_estimate_local_only',
            field=models.BooleanField(default=False, help_text='Only estimate local body motion (no global trajectory)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='wham_run_smplify',
            field=models.BooleanField(default=False, help_text='Run SMPLify refinement (slower but more accurate)'),
        ),
    ]
