# Generated by Django 6.0.2 on 2026-03-01 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_appsettings_gvhmr_focal_length_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='gvhmr_focal_length_mm',
            field=models.FloatField(default=0, help_text='Camera focal length in mm (0 = auto-detect)'),
        ),
        migrations.CreateModel(
            name='PhotoAnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('photo_file', models.CharField(max_length=500)),
                ('backend', models.CharField(choices=[('smplest_x', 'SMPLest-X'), ('pymafx', 'PyMAF-X'), ('hmr2', 'HMR 2.0'), ('mediapipe', 'MediaPipe')], default='smplest_x', max_length=30)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('body_type', models.CharField(blank=True, max_length=100)),
                ('result_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['backend', '-created_at'], name='core_photoa_backend_befde4_idx')],
            },
        ),
    ]
