# Generated by Django 6.0.2 on 2026-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_result_image_to_photo_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoanalysisjob',
            name='duration_seconds',
            field=models.FloatField(default=0.0),
        ),
    ]
