# Generated by Django 6.0.2 on 2026-03-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_duration_to_photo_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='selection_opacity',
            field=models.FloatField(default=0.3, help_text='Selection highlight opacity (0.0–1.0)'),
        ),
    ]
