# Generated by Django 6.0.2 on 2026-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_appsettings_default_model_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='smpl_default_betas',
            field=models.CharField(blank=True, default='0,0,0,0,0,0,0,0,0,0', help_text='Default shape betas as comma-separated floats', max_length=200),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smpl_default_color',
            field=models.CharField(blank=True, default='#88aaff', help_text='Default SMPL body color (hex)', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smpl_default_gender',
            field=models.CharField(default='female', help_text='Default SMPL gender (female/male/neutral)', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smpl_default_opacity',
            field=models.FloatField(default=0.5, help_text='Default SMPL body opacity (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smpl_default_wireframe',
            field=models.BooleanField(default=False, help_text='Default SMPL wireframe mode'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smpl_default_xoffset',
            field=models.FloatField(default=1.0, help_text='Default SMPL body X offset in meters'),
        ),
    ]
