# Generated by Django 6.0.2 on 2026-03-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_appsettings_smpl_default_betas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='smpl_default_scene',
            field=models.TextField(blank=True, default='', help_text='Default SMPL scene settings JSON (lighting, renderer, camera)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='smpl_default_opacity',
            field=models.FloatField(default=1.0, help_text='Default SMPL body opacity (0.0-1.0)'),
        ),
    ]
