# Generated by Django 6.0.2 on 2026-03-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_appsettings_smpl_default_scene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='smpl_default_humanbody_preset',
            field=models.CharField(blank=True, default='FemaleNew', help_text='Default HumanBody model preset for SMPL test page', max_length=100),
        ),
    ]
