# Generated by Django 6.0.2 on 2026-03-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_smpl_default_humanbody_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='theatre_default_animation',
            field=models.CharField(blank=True, default='', help_text='Default animation for Theatre page (format: category/name)', max_length=300),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='theatre_default_model',
            field=models.CharField(blank=True, default='FemaleWithHair', help_text='Default model preset for Theatre page', max_length=200),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='theatre_default_preset',
            field=models.CharField(blank=True, default='ballet_stage', help_text='Default lighting/camera preset for Theatre page', max_length=50),
        ),
    ]
