# Generated by Django 6.0.2 on 2026-03-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_appsettings_theatre_default_animation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='theatre_video_format',
            field=models.CharField(default='mp4', help_text='Video export format: mp4 or webm', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='theatre_video_fps',
            field=models.IntegerField(default=30, help_text='Video export frames per second: 24, 30, 60'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='theatre_video_quality',
            field=models.CharField(default='high', help_text='Video export quality: low, medium, high, ultra', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='theatre_video_resolution',
            field=models.CharField(default='1080p', help_text='Video export resolution: 720p, 1080p, 1440p, 4k', max_length=10),
        ),
    ]
