# Generated by Django 6.0.2 on 2026-03-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_appsettings_theatre_video_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bvhjob',
            name='pipeline_params',
            field=models.JSONField(blank=True, default=dict, help_text='Per-job pipeline parameters (override AppSettings defaults)'),
        ),
    ]
