# Generated by Django 6.0.2 on 2026-03-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_bvhjob_pipeline_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='bvhjob',
            name='bvh_file_face',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='bvhjob',
            name='pipeline',
            field=models.CharField(choices=[('mediapipe', 'MediaPipe'), ('openpose', 'OpenPose'), ('rtmpose', 'RTMPose'), ('vitpose', 'ViTPose'), ('yolo11', 'YOLO11-Pose'), ('v4', 'MocapNET v4'), ('gvhmr', 'GVHMR'), ('wham', 'WHAM'), ('prompthmr', 'PromptHMR'), ('hybrid_gvhmr', 'Hybrid (GVHMR + MocapNET v4)'), ('hybrid_prompthmr', 'Hybrid (PromptHMR + MocapNET v4)')], default='mediapipe', max_length=30),
        ),
    ]
