# Generated by Django 6.0.2 on 2026-03-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_appsettings_default_anim_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='lifter_3d_default',
            field=models.CharField(default='hybrid_gvhmr', help_text='Default 3D pipeline (v4/gvhmr/wham/prompthmr/hybrid_gvhmr/hybrid_prompthmr)', max_length=20),
        ),
        migrations.AlterField(
            model_name='bvhjob',
            name='pipeline',
            field=models.CharField(choices=[('mediapipe', 'MediaPipe'), ('openpose', 'OpenPose'), ('rtmpose', 'RTMPose'), ('vitpose', 'ViTPose'), ('yolo11', 'YOLO11-Pose'), ('v4', 'MocapNET v4'), ('gvhmr', 'GVHMR'), ('wham', 'WHAM'), ('prompthmr', 'PromptHMR'), ('hybrid_gvhmr', 'Hybrid (GVHMR + MocapNET v4)'), ('hybrid_prompthmr', 'Hybrid (PromptHMR + MocapNET v4)')], default='hybrid_gvhmr', max_length=30),
        ),
    ]
