# Generated by Django 6.0.2 on 2026-03-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_appsettings_lifter_3d_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='ui_prefs',
            field=models.JSONField(blank=True, default=dict, help_text='User UI preferences (panel sizes, layout ratios, etc.)'),
        ),
    ]
