# Generated by Django 6.0.2 on 2026-08-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_bvhfile_mtime_ns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='gvhmr_focal_length_mm',
            field=models.FloatField(default=0, help_text='Brennweite der Kamera in mm. 0 = automatisch schätzen (empfohlen) (0–200)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='gvhmr_static_cam',
            field=models.BooleanField(default=True, help_text='Statische Kamera annehmen (kein DPVO). Empfohlen für eine feste Kameraperspektive'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='mp_min_detection_confidence',
            field=models.FloatField(default=0.5, help_text='Mindest-Konfidenz, damit eine Pose als erkannt gilt (0.0–1.0)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='mp_min_tracking_confidence',
            field=models.FloatField(default=0.2, help_text='Mindest-Konfidenz für das Pose-Tracking zwischen Bildern. Niedrig = seltener neu erkennen (0.0–1.0)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='progress_update_interval',
            field=models.IntegerField(default=10, help_text='Nach wie vielen Bildern der Balken weiterrückt. Kleinere Werte melden häufiger und kosten etwas Rechenzeit (1–10000)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='prompthmr_static_camera',
            field=models.BooleanField(default=True, help_text='Statische Kamera annehmen. Empfohlen für die meisten Videos'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='show_rig_animations',
            field=models.BooleanField(default=False, help_text='Rig auf der Animationsseite von Anfang an einblenden'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='show_rig_config',
            field=models.BooleanField(default=False, help_text='Rig auf der Konfigurationsseite von Anfang an einblenden'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='show_rig_scene',
            field=models.BooleanField(default=False, help_text='Rig auf der Szenenseite von Anfang an einblenden'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='smpl_default_wireframe',
            field=models.BooleanField(default=False, help_text='Body als Drahtgitter anzeigen'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='v4_hcd_epochs',
            field=models.IntegerField(default=30, help_text='IK-Epochen pro Bild. Mehr Epochen verbessern die Pose-Qualität (1–200)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='v4_hcd_iterations',
            field=models.IntegerField(default=10, help_text='IK-Gradient-Descent-Iterationen pro Bild. Mehr = genauer, aber langsamer (1–100)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='v4_hcd_learning_rate',
            field=models.FloatField(default=0.001, help_text='Lernrate für den IK-Gradient-Descent-Solver (0.0001–0.1)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='v4_smoothing_cutoff',
            field=models.FloatField(default=5.0, help_text='Butterworth-Tiefpass-Grenzfrequenz. Niedrigere Werte = glattere Animation (0.5–15.0)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='v4_smoothing_sampling',
            field=models.FloatField(default=30.0, help_text='Abtastfrequenz für den Butterworth-Filter. Sollte zur Bildrate des Videos passen (10.0–120.0)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='wham_estimate_local_only',
            field=models.BooleanField(default=False, help_text='Nur die lokale Körperbewegung schätzen, keine globale Bahn'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='wham_run_smplify',
            field=models.BooleanField(default=False, help_text='SMPLify-Verfeinerung ausführen. Langsamer, aber genauer'),
        ),
    ]
