# Generated by Django 6.0.2 on 2026-08-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_appsettings_gvhmr_focal_length_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='default_anim_animations',
            field=models.CharField(blank=True, default='', help_text='Welche Animation die Animationsseite von sich aus lädt', max_length=300),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='default_anim_config',
            field=models.CharField(blank=True, default='', help_text='Welche Animation die Konfigurationsseite von sich aus lädt', max_length=300),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='default_anim_result',
            field=models.CharField(blank=True, default='', help_text='Welche Animation die Ergebnisseite von sich aus lädt', max_length=300),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='default_anim_scene',
            field=models.CharField(blank=True, default='', help_text='Welche Animation die Szenenseite von sich aus lädt', max_length=300),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='theatre_default_animation',
            field=models.CharField(blank=True, default='', help_text='Welche Animation beim Laden der Theatre-Seite abgespielt wird', max_length=300),
        ),
    ]
