# Generated by Django 6.1.1 on 2026-09-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_appsettings_default_anim_animations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='gem_static_cam',
            field=models.BooleanField(default=True, help_text='Statische Kamera annehmen. Das Video-Demo von GEM verfolgt die Kamera ohnehin nicht; der Schalter setzt nur die Kamera-Maske des Modells'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='lifter_3d_default',
            field=models.CharField(default='hybrid_gvhmr', help_text='Default 3D pipeline (v4/gvhmr/wham/prompthmr/gem/hybrid_gvhmr/hybrid_prompthmr)', max_length=20),
        ),
        migrations.AlterField(
            model_name='bvhjob',
            name='pipeline',
            field=models.CharField(choices=[('mediapipe', 'MediaPipe'), ('openpose', 'OpenPose'), ('rtmpose', 'RTMPose'), ('vitpose', 'ViTPose'), ('yolo11', 'YOLO11-Pose'), ('v4', 'MocapNET v4'), ('gvhmr', 'GVHMR'), ('wham', 'WHAM'), ('prompthmr', 'PromptHMR'), ('gem', 'GEM-SMPL'), ('hybrid_gvhmr', 'Hybrid (GVHMR + MocapNET v4)'), ('hybrid_prompthmr', 'Hybrid (PromptHMR + MocapNET v4)')], default='hybrid_gvhmr', max_length=30),
        ),
    ]
