# Generated by Django 6.1.1 on 2026-09-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_gem_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvhjob',
            name='pipeline',
            field=models.CharField(choices=[('mediapipe', 'MediaPipe'), ('openpose', 'OpenPose'), ('rtmpose', 'RTMPose'), ('vitpose', 'ViTPose'), ('yolo11', 'YOLO11-Pose'), ('v4', 'MocapNET v4'), ('gvhmr', 'GVHMR'), ('wham', 'WHAM'), ('prompthmr', 'PromptHMR'), ('gem', 'GEM-SMPL'), ('duomo', 'DuoMo'), ('hybrid_gvhmr', 'Hybrid (GVHMR + MocapNET v4)'), ('hybrid_prompthmr', 'Hybrid (PromptHMR + MocapNET v4)')], default='hybrid_gvhmr', max_length=30),
        ),
    ]
