# Generated by Django 6.1.1 on 2026-09-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_gemx_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='duomo_joint_limits',
            field=models.BooleanField(default=True, help_text='Anatomische Grenzen für Knie, Ellbogen und Hüfte im BVH anwenden. Vorgabe für die Karte auf der Uploadseite'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='duomo_smooth_sigma',
            field=models.FloatField(default=2.0, help_text='Gaußsche Glättung der Gelenkwinkel im BVH (0 = aus, 2 = Standard, 4 und mehr = stark). Vorgabe für die Karte auf der Uploadseite (0–10)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='duomo_static_cam',
            field=models.BooleanField(default=True, help_text='Statische Kamera annehmen. DuoMo liefert ohne Kamerabahn ohnehin eine feste Kamera; der Schalter ist die Vorgabe der Karte'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gem_joint_limits',
            field=models.BooleanField(default=True, help_text='Anatomische Grenzen für Knie, Ellbogen und Hüfte im BVH anwenden. Vorgabe für die Karte auf der Uploadseite'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gem_smooth_sigma',
            field=models.FloatField(default=2.0, help_text='Gaußsche Glättung der Gelenkwinkel im BVH (0 = aus, 2 = Standard, 4 und mehr = stark). Vorgabe für die Karte auf der Uploadseite (0–10)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gemx_smooth_sigma',
            field=models.FloatField(default=2.0, help_text='Gaußsche Glättung der Gelenkwinkel im BVH (0 = aus, 2 = Standard, 4 und mehr = stark). Gelenkgrenzen gibt es für GEM-X nicht: SOMA hat 77 Gelenke, die Grenzen sind SMPL-Indizes (0–10)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gemx_static_cam',
            field=models.BooleanField(default=True, help_text='Statische Kamera annehmen — wie bei GEM-SMPL nur die Kamera-Maske des Modells. Vorgabe für die Karte auf der Uploadseite'),
        ),
    ]
