# Generated by Django 6.1.1 on 2026-09-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_lifter_einstellungen'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='gvhmr_joint_limits',
            field=models.BooleanField(default=True, help_text='Anatomische Grenzen für Knie, Ellbogen und Hüfte im BVH anwenden. Vorgabe für die Karte auf der Uploadseite'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gvhmr_smooth_sigma',
            field=models.FloatField(default=2.0, help_text='Gaußsche Glättung der Gelenkwinkel im BVH (0 = aus, 2 = Standard, 4 und mehr = stark). Vorgabe für die Karte auf der Uploadseite; gilt auch für den Körper-Durchlauf des Hybrid-Laufs (0–10)'),
        ),
    ]
