# Generated by Django 6.1.1 on 2026-09-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_gvhmr_glaettung'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='gem_render',
            field=models.BooleanField(default=False, help_text='Kamera-, Welt- und Vergleichsvideo mit Open3D erzeugen (dauert länger, liest das Video komplett in den Speicher). Vorgabe für die Karte'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gvhmr_use_dpvo',
            field=models.BooleanField(default=False, help_text='Kamerabahn mit DPVO statt SimpleVO schätzen (genauer, langsamer, mehr VRAM). Wirkt nur ohne statische Kamera. Vorgabe für die Karte'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gvhmr_verbose',
            field=models.BooleanField(default=False, help_text='Debug-Videos der Vorstufen ausgeben (Personenkästen, ViTPose-Skelett) — liest das Video dafür komplett in den Speicher. Vorgabe für die Karte'),
        ),
    ]
