# Generated by Django 6.1.1 on 2026-09-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_dpvo_verbose_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='gvhmr_render',
            field=models.BooleanField(default=True, help_text='Kamera-, Welt- und Vergleichsvideo erzeugen (pytorch3d). Bei 7.538 Bildern die Hälfte der Laufzeit; ohne sie bleibt das BVH. Die Videos kopiert „3D Video Output" in den Ausgabeordner'),
        ),
    ]
