# Generated by Django 6.1.1 on 2026-09-12 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_gvhmr_render'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effektauftrag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pipeline', models.CharField(choices=[('kleid_wind', 'Kleid + Wind (Blender)')], default='kleid_wind', max_length=30)),
                ('bvh_pfad', models.CharField(max_length=512)),
                ('kleid', models.CharField(blank=True, max_length=512)),
                ('parameter', models.JSONField(blank=True, default=dict)),
                ('ausgabe', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Wartet'), ('running', 'Läuft'), ('complete', 'Fertig'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('progress_detail', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('log_pfad', models.CharField(blank=True, max_length=512)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('bericht', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
