# Generated by Django 6.1.1 on 2026-09-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_hybrid_gem_haende'),
    ]

    operations = [
        migrations.AddField(
            model_name='effektauftrag',
            name='modell',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='effektauftrag',
            name='pipeline',
            field=models.CharField(choices=[('kleid_wind', 'Kleid + Wind (Blender, MPFB-Figur)'), ('figur_def', 'HumanBody-Figur (DEF-Skelett, pyrender)')], default='kleid_wind', max_length=30),
        ),
    ]
