# Generated by Django 6.1.1 on 2026-09-12 17:37

# -*- coding: utf-8 -*-
u"""Vorgaben der Effekte-Seite (`EffektEinstellungen`, abstrakte Basis von
`AppSettings`): Pipeline, Modell (Female2), Animation, Windrichtung, Bildrate,
Breite, Hoehe, Wind. Edgar, 12.09.2026: „erstelle eine Seite Einstellungen -
Effekte".
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_hybrid_gem_vorgabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='effekte_default_animation',
            field=models.CharField(blank=True, default='', help_text='Welche Animation die Effekte-Seite beim Laden vorwählt; ohne Angabe die neueste passende aus „Process Videos"', max_length=300),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='effekte_default_model',
            field=models.CharField(blank=True, default='Female2', help_text='Vorgewähltes HumanBody-Modell der Effekte-Seite', max_length=200),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='effekte_default_pipeline',
            field=models.CharField(blank=True, default='figur_def', help_text='Vorgewählte Pipeline der Effekte-Seite (kleid_wind, figur_def)', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='effekte_video_fps',
            field=models.IntegerField(default=30, help_text='Bilder je Sekunde des Videos; bei 60-fps-BVHs gibt 30 den Schritt 1, 24 gäbe Zeitlupe (10–60)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='effekte_video_height',
            field=models.IntegerField(default=900, help_text='Videohöhe — Vorgabe des Reglers auf der Effekte-Seite (240–2160)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='effekte_video_width',
            field=models.IntegerField(default=720, help_text='Videobreite — Vorgabe des Reglers auf der Effekte-Seite (320–3840)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='effekte_wind',
            field=models.FloatField(default=4.0, help_text='Windstärke der Stoffdynamik (HumanBody-Figur); 0 = kein Wind (0–30)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='effekte_windrichtung',
            field=models.CharField(blank=True, default='seite', help_text='Windrichtung relativ zur Figur (seite, vorn, hinten)', max_length=10),
        ),
    ]
