# Generated by Django 6.1.1 on 2026-09-18 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_netzqualitaet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildmodellauftrag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kennung', models.CharField(max_length=19, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('genesis9', 'Genesis 9')], default='genesis9', max_length=20)),
                ('status', models.CharField(choices=[('angelegt', 'Angelegt'), ('laeuft', 'Läuft'), ('fertig', 'Fertig'), ('gescheitert', 'Fehlgeschlagen'), ('angehalten', 'Angehalten')], default='angelegt', max_length=20)),
                ('schritt', models.CharField(blank=True, max_length=30)),
                ('progress', models.IntegerField(default=0)),
                ('progress_detail', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('optionen', models.JSONField(blank=True, default=dict)),
                ('bilder', models.JSONField(blank=True, default=list)),
                ('ergebnis', models.JSONField(blank=True, default=dict)),
                ('modell', models.CharField(blank=True, max_length=255)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='bvhjob',
            name='pipeline',
            field=models.CharField(choices=[('mediapipe', 'MediaPipe'), ('openpose', 'OpenPose'), ('rtmpose', 'RTMPose'), ('vitpose', 'ViTPose'), ('yolo11', 'YOLO11-Pose'), ('v4', 'MocapNET v4'), ('gvhmr', 'GVHMR'), ('wham', 'WHAM'), ('prompthmr', 'PromptHMR'), ('gem', 'GEM-SMPL'), ('duomo', 'DuoMo'), ('gemx', 'GEM-X (mit Händen)'), ('smplx', 'SMPL-X (eigen: Körper, Hände, Gesicht)'), ('hybrid_gvhmr', 'Hybrid (GVHMR + MocapNET v4)'), ('hybrid_prompthmr', 'Hybrid (PromptHMR + MocapNET v4)'), ('hybrid_gem', 'Hybrid (GEM-SMPL + MocapNET v4)')], default='hybrid_gvhmr', max_length=30),
        ),
    ]
