# Generated by Django 6.1.1 on 2026-09-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_bildmodellauftrag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='default_model_animations',
            field=models.CharField(blank=True, default='femaleWithClothes', help_text='HumanBody-Modell, das beim Öffnen der Animationen-Seite geladen wird', max_length=200),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='default_model_config',
            field=models.CharField(blank=True, default='femaleWithClothes', help_text='HumanBody-Modell, das beim Öffnen der Konfigurationsseite geladen wird', max_length=200),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='default_model_result',
            field=models.CharField(blank=True, default='femaleWithClothes', help_text='HumanBody-Modell, das beim Öffnen der Ergebnisseite geladen wird', max_length=200),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='default_model_scene',
            field=models.CharField(blank=True, default='femaleWithClothes', help_text='Modell, das beim Öffnen der Szene-Seite geladen wird — jede Figurart (HumanBody, SMPL-X, MakeHuman, UMA, UMA Python, Genesis 9)', max_length=200),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='effekte_default_model',
            field=models.CharField(blank=True, default='Female2', help_text='HumanBody-Modell (Pipeline „HumanBody-Figur"), das die Effekte-Seite beim Laden vorwählt. Ein Modell, das es nicht mehr gibt, bleibt unbesetzt', max_length=200),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='smpl_default_humanbody_preset',
            field=models.CharField(blank=True, default='FemaleNew', help_text='HumanBody-Modell neben dem SMPL-Körper auf der SMPL-Seite', max_length=100),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='theatre_default_model',
            field=models.CharField(blank=True, default='FemaleWithHair', help_text='HumanBody-Modell, das beim Laden der Theatre-Seite angezeigt wird', max_length=200),
        ),
    ]
