# Generated by Django 6.1.1 on 2026-09-26 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_standardmodell_hilfetexte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meshauftrag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kennung', models.CharField(max_length=19, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('angelegt', 'Angelegt'), ('laeuft', 'Läuft'), ('fertig', 'Fertig'), ('gescheitert', 'Fehlgeschlagen'), ('angehalten', 'Angehalten')], default='angelegt', max_length=20)),
                ('schritt', models.CharField(blank=True, max_length=30)),
                ('progress', models.IntegerField(default=0)),
                ('progress_detail', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('optionen', models.JSONField(blank=True, default=dict)),
                ('bilder', models.JSONField(blank=True, default=list)),
                ('ergebnis', models.JSONField(blank=True, default=dict)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
