# Generated by Django 6.1.1 on 2026-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_haarengineauftrag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haarengineauftrag',
            name='status',
            field=models.CharField(choices=[('angelegt', 'Angelegt'), ('laeuft', 'Läuft'), ('fertig', 'Fertig'), ('gescheitert', 'Fehlgeschlagen'), ('angehalten', 'Angehalten'), ('wartet', 'Wartet auf Begutachtung')], default='angelegt', max_length=20),
        ),
    ]
