from django.urls import path
from . import views
from . import character_api
from . import test_character_api

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('process/', views.upload_video, name='upload'),
    path('process/v4/', views.upload_video_v4, name='upload_v4'),
    path('process/list/', views.processed_list, name='processed'),
    path('process/<uuid:job_id>/', views.job_status, name='job_status'),
    path('process/<uuid:job_id>/start/', views.start_processing, name='start_processing'),
    path('process/<uuid:job_id>/stop/', views.stop_processing, name='stop_processing'),
    path('process/<uuid:job_id>/result/', views.job_result, name='job_result'),
    path('process/<uuid:job_id>/delete/', views.delete_job, name='delete_job'),
    path('api/bvh/<uuid:job_id>/', views.serve_bvh_file, name='serve_bvh'),
    path('api/thumbnail/<uuid:job_id>/', views.video_thumbnail, name='video_thumbnail'),
    path('api/detection/<uuid:job_id>/', views.serve_detection_data, name='serve_detection'),
    path('api/keypoints/<uuid:job_id>/', views.serve_keypoints_2d, name='serve_keypoints'),
    path('api/rig-video/<uuid:job_id>/', views.save_rig_video, name='save_rig_video'),
    path('api/overlay-video/<uuid:job_id>/', views.save_overlay_video, name='save_overlay_video'),
    path('api/video3d/<uuid:job_id>/', views.save_video3d, name='save_video3d'),
    path('library/', views.bvh_library, name='library'),
    path('library/scan/', views.scan_bvh_files, name='scan_bvh'),
    path('library/<int:pk>/delete/', views.delete_bvh, name='delete_bvh'),
    path('library/<int:pk>/blender/', views.open_in_blender, name='open_in_blender'),
    path('webcam/', views.webcam, name='webcam'),
    path('settings/', views.app_settings, name='settings'),
    path('settings/model/', views.app_settings_model, name='settings_model'),
    path('settings/video-to-bvh/', views.app_settings_videobvh, name='settings_videobvh'),
    path('settings/video-to-bvh-2d/', views.app_settings_videobvh_2d, name='settings_videobvh_2d'),
    path('settings/video-to-bvh-3d/', views.app_settings_videobvh_3d, name='settings_videobvh_3d'),
    path('api/job/<uuid:job_id>/start/', views.api_start_processing, name='api_start_processing'),
    path('api/job/<uuid:job_id>/stop/', views.api_stop_processing, name='api_stop_processing'),
    path('api/job/<uuid:job_id>/status/', views.job_status_api, name='job_status_api'),
    path('api/job/<uuid:job_id>/delete/', views.delete_job_api, name='delete_job_api'),
    path('api/jobs/bulk-delete/', views.bulk_delete_jobs, name='bulk_delete_jobs'),

    # HumanBody
    path('humanbody/photo-to-3d/', character_api.photo_to_3d_page, name='photo_to_3d'),
    path('api/character/analyze-photo/', character_api.analyze_photo, name='analyze_photo'),
    path('api/character/analyze-photo/status/', character_api.analyze_photo_status, name='analyze_photo_status'),
    path('api/character/smplx-mesh/', character_api.smplx_mesh, name='smplx_mesh'),
    path('humanbody/config/', character_api.character_viewer, name='humanbody_config'),
    path('humanbody/scene/', character_api.scene_config, name='humanbody_scene'),
    path('humanbody/animations/', character_api.animations_page, name='humanbody_animations'),
    path('humanbody/test-animation/', character_api.test_animation_page, name='test_animation'),
    path('humanbody/test-character/', character_api.test_character_page, name='test_character'),
    path('api/character/mesh/', character_api.character_mesh, name='character_mesh'),
    path('api/character/morphs/', character_api.character_morphs, name='character_morphs'),
    path('api/character/rig/', character_api.character_rig, name='character_rig'),
    path('api/character/def-skeleton/', character_api.character_def_skeleton, name='character_def_skeleton'),
    path('api/character/skin-weights/', character_api.character_skin_weights, name='character_skin_weights'),
    path('api/character/wardrobe/', character_api.character_wardrobe, name='character_wardrobe'),
    path('api/character/animations/', character_api.character_animations, name='character_animations'),
    path('api/character/models/', character_api.character_models, name='character_models'),
    path('api/character/model/save/', character_api.character_model_save, name='character_model_save'),
    path('api/character/model/<str:name>/', character_api.character_model_detail, name='character_model_detail'),
    path('api/settings/humanbody/', character_api.humanbody_settings_api, name='humanbody_settings_api'),
    path('api/character/asset/<str:name>/', character_api.character_asset_glb, name='character_asset_glb'),
    path('api/character/bvh/<str:category>/<str:name>/', character_api.character_bvh_file_cat, name='character_bvh_file_cat'),
    path('api/character/bvh/<str:name>/', character_api.character_bvh_file, name='character_bvh_file'),

    # Cloth
    path('api/character/cloth/', character_api.character_cloth, name='character_cloth'),
    path('api/character/cloth/regions/', character_api.character_cloth_regions, name='character_cloth_regions'),
    path('api/character/cloth/presets/', character_api.cloth_preset_list, name='cloth_preset_list'),
    path('api/character/cloth/presets/save/', character_api.cloth_preset_save, name='cloth_preset_save'),
    path('api/character/cloth/presets/<str:category>/<str:name>/', character_api.cloth_preset_detail, name='cloth_preset_detail'),

    # Hair
    path('api/character/hairstyles/', character_api.character_hairstyles, name='character_hairstyles'),
    path('api/character/hairstyle/<str:name>/', character_api.character_hairstyle_glb, name='character_hairstyle_glb'),

    # Test Character API (isolated version from TestCharakter/)
    path('api/character-test/mesh/', test_character_api.test_character_mesh, name='test_character_mesh'),
    path('api/character-test/morphs/', test_character_api.test_character_morphs, name='test_character_morphs'),
    path('api/character-test/skin-weights/', test_character_api.test_character_skin_weights, name='test_character_skin_weights'),
    path('api/character-test/def-skeleton/', test_character_api.test_character_def_skeleton, name='test_character_def_skeleton'),
    path('api/character-test/version/', test_character_api.test_version_info, name='test_version_info'),
    path('api/character-test/source/', test_character_api.test_character_source, name='test_character_source'),
    path('api/character-test/reload/', test_character_api.test_reload, name='test_reload'),
    path('api/character-test/switch/', test_character_api.test_switch_character, name='test_switch_character'),
]
