from django.urls import path
from . import views
from . import character_api
from . import test_character_api

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('process/', views.upload_video, name='upload'),
    path('process/VideoToBVH/', views.upload_video_v4, name='upload_v4'),
    path('process/list/', views.processed_list, name='processed'),
    path('process/result/', views.standalone_result, name='standalone_result'),
    path('process/<uuid:job_id>/', views.job_status, name='job_status'),
    path('process/<uuid:job_id>/start/', views.start_processing, name='start_processing'),
    path('process/<uuid:job_id>/stop/', views.stop_processing, name='stop_processing'),
    path('process/<uuid:job_id>/result/', views.job_result, name='job_result'),
    path('process/<uuid:job_id>/delete/', views.delete_job, name='delete_job'),
    path('api/bvh/<uuid:job_id>/', views.serve_bvh_file, name='serve_bvh'),
    path('api/bvh-face/<uuid:job_id>/', views.serve_bvh_face, name='serve_bvh_face'),
    path('api/video/<uuid:job_id>/', views.serve_video_file, name='serve_video'),
    path('api/thumbnail/<uuid:job_id>/', views.video_thumbnail, name='video_thumbnail'),
    path('api/detection/<uuid:job_id>/', views.serve_detection_data, name='serve_detection'),
    path('api/keypoints/<uuid:job_id>/', views.serve_keypoints_2d, name='serve_keypoints'),
    path('api/rig-video/<uuid:job_id>/', views.save_rig_video, name='save_rig_video'),
    path('api/overlay-video/<uuid:job_id>/', views.save_overlay_video, name='save_overlay_video'),
    path('api/video3d/<uuid:job_id>/', views.save_video3d, name='save_video3d'),
    path('test/mocapnet/', views.test_mocapnet, name='test_mocapnet'),
    path('library/', views.bvh_library, name='library'),
    path('library/scan/', views.scan_bvh_files, name='scan_bvh'),
    path('library/<int:pk>/delete/', views.delete_bvh, name='delete_bvh'),
    path('library/<int:pk>/blender/', views.open_in_blender, name='open_in_blender'),
    path('webcam/', views.webcam, name='webcam'),
    path('settings/', views.app_settings, name='settings'),
    path('settings/model/', views.app_settings_model, name='settings_model'),
    path('settings/result/', views.app_settings_result, name='settings_result'),
    path('settings/scene/', views.app_settings_scene, name='settings_scene'),
    path('settings/video-to-bvh/', views.app_settings_videobvh, name='settings_videobvh'),
    path('settings/video-to-bvh-2d/', views.app_settings_videobvh_2d, name='settings_videobvh_2d'),
    path('settings/video-to-bvh-3d/', views.app_settings_videobvh_3d, name='settings_videobvh_3d'),
    path('settings/smpl/', views.app_settings_smpl, name='settings_smpl'),
    path('settings/theatre/', character_api.theatre_settings_page, name='settings_theatre'),
    path('settings/bvh-studio/', character_api.bvh_studio_settings_page, name='settings_bvh_studio'),
    path('api/job/<uuid:job_id>/start/', views.api_start_processing, name='api_start_processing'),
    path('api/job/<uuid:job_id>/stop/', views.api_stop_processing, name='api_stop_processing'),
    path('api/job/<uuid:job_id>/status/', views.job_status_api, name='job_status_api'),
    path('api/job/<uuid:job_id>/delete/', views.delete_job_api, name='delete_job_api'),
    path('api/jobs/bulk-delete/', views.bulk_delete_jobs, name='bulk_delete_jobs'),
    path('api/job/create-from-file/', views.create_job_from_file, name='create_job_from_file'),

    # HumanBody
    path('humanbody/photo-to-3d/', character_api.photo_to_3d_page, name='photo_to_3d'),
    path('humanbody/photo-to-3d/jobs/', character_api.photo_analysis_jobs_page, name='photo_analysis_jobs'),
    path('api/character/analyze-photo/', character_api.analyze_photo, name='analyze_photo'),
    path('api/character/analyze-photo/status/', character_api.analyze_photo_status, name='analyze_photo_status'),
    path('api/character/photo-job/<uuid:job_id>/', character_api.photo_analysis_job_data, name='photo_analysis_job_data'),
    path('api/character/photo-job/<uuid:job_id>/screenshot/', character_api.photo_analysis_save_screenshot, name='photo_analysis_save_screenshot'),
    path('api/character/photo-job/<uuid:job_id>/reprocess/', character_api.photo_analysis_reprocess, name='photo_analysis_reprocess'),
    path('api/character/photo-job/<uuid:job_id>/delete/', character_api.photo_analysis_delete, name='photo_analysis_delete'),
    path('api/character/photo-jobs/bulk-delete/', character_api.photo_analysis_bulk_delete, name='photo_analysis_bulk_delete'),
    path('api/character/photo-job/<uuid:job_id>/silhouette/', character_api.photo_silhouette_data, name='photo_silhouette_data'),
    path('api/character/photo-job/<uuid:job_id>/save-alignment/', character_api.photo_save_alignment, name='photo_save_alignment'),
    path('api/character/photo-job/<uuid:job_id>/save-projection/', character_api.photo_save_projection, name='photo_save_projection'),
    path('api/character/smplx-mesh/', character_api.smplx_mesh, name='smplx_mesh'),
    path('api/character/smplx-texture/<uuid:job_id>/', character_api.smplx_texture, name='smplx_texture'),
    path('humanbody/config/', character_api.character_viewer, name='humanbody_config'),
    path('humanbody/scene/', character_api.scene_config, name='humanbody_scene'),
    path('humanbody/scene-model/', character_api.scene_model, name='humanbody_scene_model'),
    path('humanbody/theatre/', character_api.theatre_page, name='theatre'),
    path('humanbody/bvh-studio/', character_api.bvh_studio_page, name='bvh_studio'),
    path('humanbody/theatre-studio/', character_api.theatre_studio_page, name='theatre_studio'),
    path('humanbody/theatre/help/', character_api.theatre_help_page, name='theatre_help'),
    path('humanbody/rigging/help/', character_api.rigging_help_page, name='rigging_help'),
    path('api/ui-pref/', character_api.ui_pref_save, name='ui_pref_save'),
    path('api/character/mh-proxy-fit/', character_api.mh_proxy_fit, name='mh_proxy_fit'),
    path('humanbody/animations/', character_api.animations_page, name='humanbody_animations'),
    path('humanbody/test-animation/', character_api.test_animation_page, name='test_animation'),
    path('humanbody/test-character/', character_api.test_character_page, name='test_character'),
    path('api/character/mesh/', character_api.character_mesh, name='character_mesh'),
    path('api/character/morphs/', character_api.character_morphs, name='character_morphs'),
    path('api/character/rig/', character_api.character_rig, name='character_rig'),
    path('api/character/rigify-skeleton/', character_api.character_rigify_skeleton, name='character_rigify_skeleton'),
    path('api/character/skin-weights/', character_api.character_skin_weights, name='character_skin_weights'),
    path('api/character/retarget-config/', character_api.retarget_config, name='retarget_config'),
    path('api/retarget/', character_api.retarget, name='retarget'),
    path('api/character/retarget-bvh/<str:category>/<str:name>/', character_api.retarget_bvh, name='retarget_bvh'),  # legacy
    path('api/character/retarget-merge/', character_api.retarget_merge, name='retarget_merge'),
    path('api/character/retarget-job/<uuid:job_id>/', character_api.retarget_job_bvh, name='retarget_job_bvh'),  # legacy
    path('api/character/retarget-job-merge/<uuid:job_id>/', character_api.retarget_job_merge, name='retarget_job_merge'),
    path('api/character/retarget-bvh-text/', character_api.retarget_bvh_text, name='retarget_bvh_text'),
    path('api/character/save-bvh-text/', character_api.save_bvh_text, name='save_bvh_text'),
    path('api/character/bvh-manage/', character_api.bvh_manage, name='bvh_manage'),
    path('api/studio/project-save/', character_api.studio_project_save, name='studio_project_save'),
    path('api/studio/project-load/', character_api.studio_project_load, name='studio_project_load'),
    path('api/studio/project-list/', character_api.studio_project_list, name='studio_project_list'),
    path('api/character/wardrobe/', character_api.character_wardrobe, name='character_wardrobe'),
    path('api/character/animations/', character_api.character_animations, name='character_animations'),
    path('api/character/model-files/', character_api.model_files, name='model_files'),
    path('api/character/scenes/', character_api.scene_list, name='scene_list'),
    path('api/character/scene/save/', character_api.scene_save, name='scene_save'),
    path('api/character/scene/<str:name>/', character_api.scene_detail, name='scene_detail'),
    path('api/character/models/', character_api.character_models, name='character_models'),
    path('api/character/model/save/', character_api.character_model_save, name='character_model_save'),
    path('api/character/model/<str:name>/', character_api.character_model_detail, name='character_model_detail'),
    path('api/settings/humanbody/', character_api.humanbody_settings_api, name='humanbody_settings_api'),
    path('api/settings/theatre/', character_api.theatre_settings_api, name='theatre_settings_api'),
    path('api/theatre/convert-video/', character_api.theatre_convert_video, name='theatre_convert_video'),
    path('api/theatre/render-video/', character_api.theatre_render_video, name='theatre_render_video'),
    path('api/theatre/encode-frames/', character_api.theatre_encode_frames, name='theatre_encode_frames'),
    path('api/settings/smpl/', character_api.smpl_settings_api, name='smpl_settings_api'),
    path('api/settings/smpl/save/', character_api.smpl_settings_save, name='smpl_settings_save'),
    path('api/ui-prefs/', views.ui_prefs_api, name='ui_prefs_api'),
    path('api/character/asset/<str:name>/', character_api.character_asset_glb, name='character_asset_glb'),
    path('api/character/bvh/<str:category>/<str:name>/', character_api.character_bvh_file_cat, name='character_bvh_file_cat'),
    path('api/character/bvh/<str:name>/', character_api.character_bvh_file, name='character_bvh_file'),
    path('api/character/animation/save/', character_api.animation_save, name='animation_save'),

    # Cloth
    path('api/character/cloth/', character_api.character_cloth, name='character_cloth'),
    path('api/character/cloth/regions/', character_api.character_cloth_regions, name='character_cloth_regions'),
    path('api/character/cloth/presets/', character_api.cloth_preset_list, name='cloth_preset_list'),
    path('api/character/cloth/presets/save/', character_api.cloth_preset_save, name='cloth_preset_save'),
    path('api/character/cloth/presets/<str:category>/<str:name>/', character_api.cloth_preset_detail, name='cloth_preset_detail'),

    # Vertex Editor
    path('api/character/vertex-edit/smooth/', character_api.vertex_edit_smooth, name='vertex_edit_smooth'),
    path('api/character/vertex-edit/push-outside/', character_api.vertex_edit_push_outside, name='vertex_edit_push_outside'),

    # Pattern Editor
    path('api/character/pattern/generate/', character_api.pattern_generate, name='pattern_generate'),
    path('api/character/pattern/save/', character_api.pattern_save, name='pattern_save'),
    path('api/character/pattern/specification/', character_api.pattern_specification, name='pattern_specification'),
    path('api/character/pattern/region/generate/', character_api.pattern_region_generate, name='pattern_region_generate'),

    # Hair
    path('api/character/hairstyles/', character_api.character_hairstyles, name='character_hairstyles'),
    path('api/character/hairstyle/<str:name>/', character_api.character_hairstyle_glb, name='character_hairstyle_glb'),

    # Garment Fitter
    path('api/character/garment/library/', character_api.garment_library, name='garment_library'),
    path('api/character/garment/library/rescan/', character_api.garment_library_rescan, name='garment_library_rescan'),
    path('api/character/garment/fit/', character_api.garment_fit, name='garment_fit'),
    path('api/character/garment/export/', character_api.garment_export, name='garment_export'),
    path('api/character/garment/download/available/', character_api.garment_download_available, name='garment_download_available'),
    path('api/character/garment/download/', character_api.garment_download, name='garment_download'),
    path('api/character/garment/thumb/<path:garment_path>/', character_api.garment_thumbnail, name='garment_thumbnail'),

    # SMPL Garments
    path('humanbody/test-smpl/', character_api.smpl_test_page, name='test_smpl'),
    path('api/smpl/body/', character_api.smpl_body_mesh, name='smpl_body_mesh'),
    path('api/smpl/garment/library/', character_api.smpl_garment_library, name='smpl_garment_library'),
    path('api/smpl/garment/mesh/', character_api.smpl_garment_mesh, name='smpl_garment_mesh'),
    path('api/smpl/garment/fit/', character_api.smpl_garment_fit, name='smpl_garment_fit'),
    path('api/smpl/garment/thumb/<path:garment_path>/', character_api.smpl_garment_thumbnail, name='smpl_garment_thumbnail'),

    # Test Character API (isolated version from TestCharakter/)
    path('api/character-test/mesh/', test_character_api.test_character_mesh, name='test_character_mesh'),
    path('api/character-test/morphs/', test_character_api.test_character_morphs, name='test_character_morphs'),
    path('api/character-test/skin-weights/', test_character_api.test_character_skin_weights, name='test_character_skin_weights'),
    path('api/character-test/rigify-skeleton/', test_character_api.test_character_rigify_skeleton, name='test_character_rigify_skeleton'),
    path('api/character-test/version/', test_character_api.test_version_info, name='test_version_info'),
    path('api/character-test/source/', test_character_api.test_character_source, name='test_character_source'),
    path('api/character-test/reload/', test_character_api.test_reload, name='test_reload'),
    path('api/character-test/switch/', test_character_api.test_switch_character, name='test_switch_character'),
]
