from django.urls import path
from .api import auftraege, auftrag_upload, bibliothek, bvhdateien, bvhtext, dateien, einstellungen, fotoauftraege, fotoausrichtung, kleidung, kleidungsbibliothek, kleidungsvorlagen, mhproxy, modelldateien, netz, netzbearbeitung, posen, retarget, schnittmuster, schnittmuster_ablage, seiten, seiten_web, skelettdaten, smpl, smplx_ausgabe, studio, studio_projekt, studio_video, system
from . import test_character_api
from . import cloth_export_api

urlpatterns = [
    path('', seiten_web.dashboard, name='dashboard'),
    # Die Auslastungs-Leiste (GPU/VRAM/Temp/CPU/RAM/Netz) hat hier KEINEN Endpunkt
    # mehr: sie kommt seit 12.08.2026 aus djangoBase und antwortet unter
    # /help/api/system-stats/ (ui/urls.py bindet djangobase.urls auf help/ ein).
    path('process/', auftrag_upload.upload_video, name='upload'),
    path('process/VideoToBVH/', auftrag_upload.upload_video_v4, name='upload_v4'),
    path('process/list/', seiten_web.processed_list, name='processed'),
    path('process/result/', seiten_web.standalone_result, name='standalone_result'),
    path('process/<uuid:job_id>/', seiten_web.job_status, name='job_status'),
    path('process/<uuid:job_id>/start/', auftraege.start_processing, name='start_processing'),
    path('process/<uuid:job_id>/stop/', auftraege.stop_processing, name='stop_processing'),
    path('process/<uuid:job_id>/result/', seiten_web.job_result, name='job_result'),
    path('process/<uuid:job_id>/delete/', auftraege.delete_job, name='delete_job'),
    path('api/bvh/<uuid:job_id>/', dateien.serve_bvh_file, name='serve_bvh'),
    path('api/bvh-face/<uuid:job_id>/', dateien.serve_bvh_face, name='serve_bvh_face'),
    path('api/video/<uuid:job_id>/', dateien.serve_video_file, name='serve_video'),
    path('api/thumbnail/<uuid:job_id>/', dateien.video_thumbnail, name='video_thumbnail'),
    path('api/detection/<uuid:job_id>/', dateien.serve_detection_data, name='serve_detection'),
    path('api/keypoints/<uuid:job_id>/', dateien.serve_keypoints_2d, name='serve_keypoints'),
    path('api/rig-video/<uuid:job_id>/', dateien.save_rig_video, name='save_rig_video'),
    path('api/overlay-video/<uuid:job_id>/', dateien.save_overlay_video, name='save_overlay_video'),
    path('api/video3d/<uuid:job_id>/', dateien.save_video3d, name='save_video3d'),
    path('test/mocapnet/', seiten_web.test_mocapnet, name='test_mocapnet'),
    path('library/', seiten_web.bvh_library, name='library'),
    path('library/scan/', bibliothek.scan_bvh_files, name='scan_bvh'),
    path('library/<int:pk>/delete/', bibliothek.delete_bvh, name='delete_bvh'),
    path('library/<int:pk>/blender/', bibliothek.open_in_blender, name='open_in_blender'),
    path('webcam/', seiten_web.webcam, name='webcam'),
    path('settings/', seiten_web.app_settings, name='settings'),
    path('settings/model/', einstellungen.app_settings_model, name='settings_model'),
    path('settings/result/', einstellungen.app_settings_result, name='settings_result'),
    path('settings/scene/', einstellungen.app_settings_scene, name='settings_scene'),
    path('settings/video-to-bvh/', seiten_web.app_settings_videobvh, name='settings_videobvh'),
    path('settings/video-to-bvh-2d/', einstellungen.app_settings_videobvh_2d, name='settings_videobvh_2d'),
    path('settings/video-to-bvh-3d/', einstellungen.app_settings_videobvh_3d, name='settings_videobvh_3d'),
    path('settings/smpl/', einstellungen.app_settings_smpl, name='settings_smpl'),
    path('settings/theatre/', seiten.theatre_settings_page, name='settings_theatre'),
    path('settings/bvh-studio/', seiten.bvh_studio_settings_page, name='settings_bvh_studio'),
    path('api/job/<uuid:job_id>/start/', auftraege.api_start_processing, name='api_start_processing'),
    path('api/job/<uuid:job_id>/stop/', auftraege.api_stop_processing, name='api_stop_processing'),
    path('api/job/<uuid:job_id>/status/', auftraege.job_status_api, name='job_status_api'),
    path('api/job/<uuid:job_id>/delete/', auftraege.delete_job_api, name='delete_job_api'),
    path('api/jobs/bulk-delete/', auftraege.bulk_delete_jobs, name='bulk_delete_jobs'),
    path('api/job/create-from-file/', auftraege.create_job_from_file, name='create_job_from_file'),

    # HumanBody
    path('humanbody/photo-to-3d/', seiten.photo_to_3d_page, name='photo_to_3d'),
    path('humanbody/photo-to-3d/jobs/', seiten.photo_analysis_jobs_page, name='photo_analysis_jobs'),
    path('api/character/analyze-photo/', fotoauftraege.analyze_photo, name='analyze_photo'),
    path('api/character/analyze-photo/status/', fotoauftraege.analyze_photo_status, name='analyze_photo_status'),
    path('api/character/photo-job/<uuid:job_id>/', fotoauftraege.photo_analysis_job_data, name='photo_analysis_job_data'),
    path('api/character/photo-job/<uuid:job_id>/screenshot/', fotoauftraege.photo_analysis_save_screenshot, name='photo_analysis_save_screenshot'),
    path('api/character/photo-job/<uuid:job_id>/reprocess/', fotoauftraege.photo_analysis_reprocess, name='photo_analysis_reprocess'),
    path('api/character/photo-job/<uuid:job_id>/delete/', fotoauftraege.photo_analysis_delete, name='photo_analysis_delete'),
    path('api/character/photo-jobs/bulk-delete/', fotoauftraege.photo_analysis_bulk_delete, name='photo_analysis_bulk_delete'),
    path('api/character/photo-job/<uuid:job_id>/silhouette/', fotoausrichtung.photo_silhouette_data, name='photo_silhouette_data'),
    path('api/character/photo-job/<uuid:job_id>/save-alignment/', fotoausrichtung.photo_save_alignment, name='photo_save_alignment'),
    path('api/character/photo-job/<uuid:job_id>/save-projection/', fotoausrichtung.photo_save_projection, name='photo_save_projection'),
    path('api/character/smplx-mesh/', smplx_ausgabe.smplx_mesh, name='smplx_mesh'),
    path('api/character/smplx-texture/<uuid:job_id>/', smplx_ausgabe.smplx_texture, name='smplx_texture'),
    path('humanbody/config/', seiten.character_viewer, name='humanbody_config'),
    path('humanbody/scene/', seiten.scene_config, name='humanbody_scene'),
    path('humanbody/scene-model/', seiten.scene_model, name='humanbody_scene_model'),
    path('humanbody/theatre/', seiten.theatre_page, name='theatre'),
    path('humanbody/bvh-studio/', seiten.bvh_studio_page, name='bvh_studio'),
    path('humanbody/theatre-studio/', seiten.theatre_studio_page, name='theatre_studio'),
    path('humanbody/theatre/help/', seiten.theatre_help_page, name='theatre_help'),
    path('humanbody/rigging/help/', seiten.rigging_help_page, name='rigging_help'),
    path('api/ui-pref/', system.ui_pref_save, name='ui_pref_save'),
    path('api/character/mh-proxy-fit/', mhproxy.mh_proxy_fit, name='mh_proxy_fit'),
    path('api/character/tpose-vertices/', mhproxy.tpose_vertices, name='tpose_vertices'),
    path('api/character/poses/', posen.list_poses, name='list_poses'),
    path('api/character/pose/<path:pose_id>/', posen.get_pose, name='get_pose'),
    path('api/character/pose-manage/', posen.pose_manage, name='pose_manage'),
    path('api/character/mh-push-outside/', mhproxy.mh_push_outside, name='mh_push_outside'),
    path('humanbody/animations/', seiten.animations_page, name='humanbody_animations'),
    path('humanbody/test-animation/', seiten.test_animation_page, name='test_animation'),
    path('humanbody/test-character/', seiten.test_character_page, name='test_character'),
    path('api/character/mesh/', netz.character_mesh, name='character_mesh'),
    path('api/character/morphs/', netz.character_morphs, name='character_morphs'),
    path('api/character/rig/', skelettdaten.character_rig, name='character_rig'),
    path('api/character/rigify-skeleton/', skelettdaten.character_rigify_skeleton, name='character_rigify_skeleton'),
    path('api/character/skin-weights/', skelettdaten.character_skin_weights, name='character_skin_weights'),
    path('api/character/retarget-config/', retarget.retarget_config, name='retarget_config'),
    path('api/retarget/', retarget.retarget, name='retarget'),
    path('api/character/retarget-bvh/<str:category>/<str:name>/', retarget.retarget_bvh, name='retarget_bvh'),  # legacy
    path('api/character/retarget-merge/', retarget.retarget_merge, name='retarget_merge'),
    path('api/character/retarget-job/<uuid:job_id>/', retarget.retarget_job_bvh, name='retarget_job_bvh'),  # legacy
    path('api/character/retarget-job-merge/<uuid:job_id>/', retarget.retarget_job_merge, name='retarget_job_merge'),
    path('api/character/retarget-bvh-text/', bvhtext.retarget_bvh_text, name='retarget_bvh_text'),
    path('api/log/', system.client_log, name='client_log'),
    path('api/retarget/smooth-bvh/', bvhtext.smooth_bvh, name='smooth_bvh'),
    path('api/retarget/save-bvh-effects/', bvhtext.save_bvh_effects, name='save_bvh_effects'),
    path('api/character/save-bvh-text/', bvhtext.save_bvh_text, name='save_bvh_text'),
    path('api/character/bvh-manage/', retarget.bvh_manage, name='bvh_manage'),
    path('api/cloth/export/', cloth_export_api.export_cloth, name='cloth_export'),
    path('api/studio/audio-upload/', studio.studio_audio_upload, name='studio_audio_upload'),
    path('api/studio/project-save/', studio_projekt.studio_project_save, name='studio_project_save'),
    path('api/studio/project-load/', studio_projekt.studio_project_load, name='studio_project_load'),
    path('api/studio/project-list/', studio_projekt.studio_project_list, name='studio_project_list'),
    path('tests/', seiten_web.testcases_page, name='testcases'),
    path('api/tests/run/', auftraege.run_testcases_api, name='run_testcases'),
    path('api/studio/theatre-presets/', studio.studio_theatre_presets, name='studio_theatre_presets'),
    path('api/studio/theatre-preset/<str:name>/', studio.studio_theatre_preset_detail, name='studio_theatre_preset_detail'),
    path('api/studio/scene-object-upload/', studio.studio_scene_object_upload, name='studio_scene_object_upload'),
    path('api/studio/floor-textures/', studio.studio_floor_textures, name='studio_floor_textures'),
    path('api/character/wardrobe/', kleidung.character_wardrobe, name='character_wardrobe'),
    path('api/character/animations/', bvhdateien.character_animations, name='character_animations'),
    path('api/character/model-files/', modelldateien.model_files, name='model_files'),
    path('api/character/scenes/', studio_projekt.scene_list, name='scene_list'),
    path('api/character/scene/save/', studio_projekt.scene_save, name='scene_save'),
    path('api/character/scene/<str:name>/', studio_projekt.scene_detail, name='scene_detail'),
    path('api/character/models/', modelldateien.character_models, name='character_models'),
    path('api/character/model/save/', modelldateien.character_model_save, name='character_model_save'),
    path('api/character/model/<str:name>/', modelldateien.character_model_detail, name='character_model_detail'),
    path('api/settings/humanbody/', system.humanbody_settings_api, name='humanbody_settings_api'),
    path('api/settings/theatre/', studio.theatre_settings_api, name='theatre_settings_api'),
    path('api/theatre/convert-video/', studio_video.theatre_convert_video, name='theatre_convert_video'),
    path('api/theatre/render-video/', studio_video.theatre_render_video, name='theatre_render_video'),
    path('api/theatre/encode-frames/', studio_video.theatre_encode_frames, name='theatre_encode_frames'),
    path('api/settings/smpl/', smpl.smpl_settings_api, name='smpl_settings_api'),
    path('api/settings/smpl/save/', smpl.smpl_settings_save, name='smpl_settings_save'),
    path('api/ui-prefs/', einstellungen.ui_prefs_api, name='ui_prefs_api'),
    path('api/animationen/<str:kategorie>/', einstellungen.animationen_der_kategorie,
         name='animationen_der_kategorie'),
    path('api/character/asset/<str:name>/', netz.character_asset_glb, name='character_asset_glb'),
    path('api/character/bvh/<str:category>/<str:name>/', bvhdateien.character_bvh_file_cat, name='character_bvh_file_cat'),
    path('api/character/bvh/<str:name>/', bvhdateien.character_bvh_file, name='character_bvh_file'),
    path('api/character/animation/save/', bvhdateien.animation_save, name='animation_save'),

    # CharMorph
    path('api/character/charmorph-presets/', system.charmorph_presets, name='charmorph_presets'),
    path('api/character/charmorph-assets/', system.charmorph_assets, name='charmorph_assets'),
    path('api/character/charmorph-hairstyles/', system.charmorph_hairstyles, name='charmorph_hairstyles'),

    # Cloth
    path('api/character/cloth/', kleidung.character_cloth, name='character_cloth'),
    path('api/character/cloth/regions/', kleidungsvorlagen.character_cloth_regions, name='character_cloth_regions'),
    path('api/character/cloth/presets/', kleidungsvorlagen.cloth_preset_list, name='cloth_preset_list'),
    path('api/character/cloth/presets/save/', kleidungsvorlagen.cloth_preset_save, name='cloth_preset_save'),
    path('api/character/cloth/presets/<str:category>/<str:name>/', kleidungsvorlagen.cloth_preset_detail, name='cloth_preset_detail'),

    # Vertex Editor
    path('api/character/vertex-edit/smooth/', netzbearbeitung.vertex_edit_smooth, name='vertex_edit_smooth'),
    path('api/character/vertex-edit/push-outside/', netzbearbeitung.vertex_edit_push_outside, name='vertex_edit_push_outside'),

    # Pattern Editor
    path('api/character/pattern/generate/', schnittmuster.pattern_generate, name='pattern_generate'),
    path('api/character/pattern/save/', schnittmuster_ablage.pattern_save, name='pattern_save'),
    path('api/character/pattern/specification/', schnittmuster_ablage.pattern_specification, name='pattern_specification'),
    path('api/character/pattern/region/generate/', schnittmuster.pattern_region_generate, name='pattern_region_generate'),

    # Hair
    path('api/character/hairstyles/', modelldateien.character_hairstyles, name='character_hairstyles'),
    path('api/character/hairstyle/<str:name>/', modelldateien.character_hairstyle_glb, name='character_hairstyle_glb'),

    # Garment Fitter
    path('api/character/garment/library/', kleidungsbibliothek.garment_library, name='garment_library'),
    path('api/character/garment/library/rescan/', kleidungsbibliothek.garment_library_rescan, name='garment_library_rescan'),
    path('api/character/garment/manage/', kleidungsbibliothek.garment_manage, name='garment_manage'),
    path('api/character/garment/fit/', kleidung.garment_fit, name='garment_fit'),
    path('api/character/garment/export/', kleidungsbibliothek.garment_export, name='garment_export'),
    path('api/character/garment/download/available/', kleidungsbibliothek.garment_download_available, name='garment_download_available'),
    path('api/character/garment/download/', kleidungsbibliothek.garment_download, name='garment_download'),
    path('api/character/garment/thumb/<path:garment_path>/', kleidungsbibliothek.garment_thumbnail, name='garment_thumbnail'),
    path('api/character/garment/texture/<path:garment_id>/<str:filename>/', kleidungsbibliothek.garment_texture, name='garment_texture'),

    # SMPL Garments
    path('humanbody/test-smpl/', seiten.smpl_test_page, name='test_smpl'),
    path('api/smpl/body/', smpl.smpl_body_mesh, name='smpl_body_mesh'),
    path('api/smpl/garment/library/', smpl.smpl_garment_library, name='smpl_garment_library'),
    path('api/smpl/garment/mesh/', smpl.smpl_garment_mesh, name='smpl_garment_mesh'),
    path('api/smpl/garment/fit/', smpl.smpl_garment_fit, name='smpl_garment_fit'),
    path('api/smpl/garment/thumb/<path:garment_path>/', smpl.smpl_garment_thumbnail, name='smpl_garment_thumbnail'),

    # Help (Logs/Versionen/Tests) jetzt aus djangoBase: /help/ -> djangobase.urls

    # Test Character API (isolated version from TestCharakter/)
    path('api/character-test/mesh/', test_character_api.test_character_mesh, name='test_character_mesh'),
    path('api/character-test/morphs/', test_character_api.test_character_morphs, name='test_character_morphs'),
    path('api/character-test/skin-weights/', test_character_api.test_character_skin_weights, name='test_character_skin_weights'),
    path('api/character-test/rigify-skeleton/', test_character_api.test_character_rigify_skeleton, name='test_character_rigify_skeleton'),
    path('api/character-test/version/', test_character_api.test_version_info, name='test_version_info'),
    path('api/character-test/source/', test_character_api.test_character_source, name='test_character_source'),
    path('api/character-test/reload/', test_character_api.test_reload, name='test_reload'),
    path('api/character-test/switch/', test_character_api.test_switch_character, name='test_switch_character'),
]
